configName: sam_l21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML21J18B
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML21_DFP\3.2.54\saml21b\atdf\ATSAML21J18B.atdf
