format_version: v1.0
type: UniqueComponent
attributes: {id: core_timer}
children:
- type: Symbols
  children:
  - type: Float
    attributes: {id: CORE_TIMER_COMPARE_MS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000.0'}
  - type: Integer
    attributes: {id: CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '100000000'}
  - type: Integer
    attributes: {id: CORE_TIMER_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '1000000'}
  - type: String
    attributes: {id: CORE_TIMER_PERIOD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '0x5f5e100'}
- type: ElementPosition
  attributes: {x: '33', y: '82', id: core_timer}
