configName: pic32mx_125_sk
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX570F512L
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.1.215\atdf\PIC32MX570F512L.atdf
