format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: ADD_LINKER_FILE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: ADVANCED_EXCEPTION}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: BSP_PIN_31_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_32_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_33_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_34_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_42_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_43_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_44_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_45_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_46_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_52_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_53_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_54_FUNCTION_NAME}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: SWITCH}
  - type: String
    attributes: {id: BSP_PIN_54_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: GPIO}
  - type: String
    attributes: {id: BSP_PIN_54_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_54_PU}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'True'}
  - type: String
    attributes: {id: BSP_PIN_55_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_58_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: U1TX}
  - type: String
    attributes: {id: BSP_PIN_58_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_59_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: U1RX}
  - type: String
    attributes: {id: BSP_PIN_59_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_60_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_61_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_63_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_7_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'false'}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: CORE_TIMER_Handler}
  - type: Boolean
    attributes: {id: CORE_TIMER_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: 'false'}
  - type: Boolean
    attributes: {id: CoreMainFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: String
    attributes: {id: CoreMainFileName}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysCallsFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysExceptionFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysInitFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysIntFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysStartupFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: Boolean
    attributes: {id: CoreSysStdioSyscallsFile}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
  - type: File
    attributes: {id: DEBUG_CONSOLE_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: EVIC_0_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: CORE_TIMER_Handler}
  - type: Boolean
    attributes: {id: EVIC_26_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_26_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: EVIC_26_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: FCE_Handler}
  - type: Boolean
    attributes: {id: EVIC_31_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: EVIC_31_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: EVIC_31_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: UART_1_Handler}
  - type: File
    attributes: {id: EXCEPTIONS_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Boolean
    attributes: {id: FCE_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: 'false'}
  - type: Boolean
    attributes: {id: FCE_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: FCE_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: FCE_Handler}
  - type: Boolean
    attributes: {id: FCE_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: nvm, value: 'false'}
  - type: File
    attributes: {id: INITIALIZATION_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: INTERRUPTS_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: INTERRUPTS_H}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: File
    attributes: {id: LINKER_SCRIPT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: File
    attributes: {id: MAIN_C}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
  - type: Hex
    attributes: {id: PMD5_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '16974622'}
  - type: Hex
    attributes: {id: PMD6_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '65537'}
  - type: Hex
    attributes: {id: SYS_PORT_D_CNPU}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64'}
  - type: Combo
    attributes: {id: SYS_PORT_PPS_INPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: U1RX}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_INPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '18'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Combo
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: RPF0}
  - type: Boolean
    attributes: {id: UART1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'true'}
  - type: Integer
    attributes: {id: UART1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '48000000'}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: UART_1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: UART_1_Handler}
  - type: Boolean
    attributes: {id: UART_1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Boolean
    attributes: {id: USE_PPS_INPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Setting
    attributes: {id: XC32_LINKER_PREPROC_MARCOS}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '240', y: '20', id: core}
