files:
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 64D0F9C57F1452BD074A574237B811D7
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64D0F9C57F1452BD074A574237B811D7
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 56F52163B0A88C9ABB89CE428F6CFCB8
  logicalPath: config/pic32mz_ef_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 56F52163B0A88C9ABB89CE428F6CFCB8
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 348E1BD972633E1AFDBDCCD133C30C5B
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 348E1BD972633E1AFDBDCCD133C30C5B
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: ED6722C1169FEA2DA1F15D907F42AA46
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: ED6722C1169FEA2DA1F15D907F42AA46
- generatedChecksum: 085AD21E69A015135F99F9AE4E244A69
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 085AD21E69A015135F99F9AE4E244A69
- generatedChecksum: 8C4F3C760E9FEC38BFA5F5E1734D3307
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8C4F3C760E9FEC38BFA5F5E1734D3307
- generatedChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
  logicalPath: config/pic32mz_ef_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
- generatedChecksum: CD1794BE8A9148BA4C835E811CBD7164
  logicalPath: config/pic32mz_ef_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CD1794BE8A9148BA4C835E811CBD7164
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A9C595E0E5A92D2B85C18D2A27597B84
  logicalPath: config/pic32mz_ef_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A9C595E0E5A92D2B85C18D2A27597B84
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config/pic32mz_ef_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: 6707BDC3F251452170841D10D69DB1F1
  logicalPath: config/pic32mz_ef_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6707BDC3F251452170841D10D69DB1F1
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: C28AA8F266DD056E96DCBE0761337241
  logicalPath: config/pic32mz_ef_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: C28AA8F266DD056E96DCBE0761337241
- generatedChecksum: 3C465EE2268CD765C11300F75C6560CC
  logicalPath: config/pic32mz_ef_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C465EE2268CD765C11300F75C6560CC
- generatedChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
  logicalPath: config/pic32mz_ef_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 4C6C4A7B7E33767128AA763FFAE2E394
- generatedChecksum: 03F4F642FB053452528D6138C4E85789
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 03F4F642FB053452528D6138C4E85789
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_sk;../src/packs/PIC32MZ2048EFH144_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
