configName: pic32mk_mcj_curiosity_pro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MK0512MCJ064
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.4.94\atdf\PIC32MK0512MCJ064.atdf
