files:
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: C4B28B6A80133AA730D79B23CAE2EBB9
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C4B28B6A80133AA730D79B23CAE2EBB9
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: AE30FE7D3AD07C5C0BE2DACE1B94CA46
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE30FE7D3AD07C5C0BE2DACE1B94CA46
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: B78784342D92F137A0446EBC260A199D
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B78784342D92F137A0446EBC260A199D
- generatedChecksum: 2F4E5BCFE488C8CD901CAAC9873FF676
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2F4E5BCFE488C8CD901CAAC9873FF676
- generatedChecksum: 36C0078FDD71E3F1055491459AFCF7F2
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36C0078FDD71E3F1055491459AFCF7F2
- generatedChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
- generatedChecksum: 8D0C633B8061C12CF522123C4B98475C
  logicalPath: config/pic32mk_mcm_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D0C633B8061C12CF522123C4B98475C
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 5D89DFD3C9769D1183177FB058F59B0D
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D89DFD3C9769D1183177FB058F59B0D
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: E117D25137D333D9E62C091362100BB0
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: E117D25137D333D9E62C091362100BB0
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: D5F328D9196C9E5B2227E83B2AA03321
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D5F328D9196C9E5B2227E83B2AA03321
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
