format_version: v1.0
type: UniqueComponent
attributes: {id: core_timer}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CORE_TIMER_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '100000000'}
  - type: Integer
    attributes: {id: CORE_TIMER_PERIOD_US}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '1000'}
  - type: String
    attributes: {id: CORE_TIMER_PERIOD_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core_timer, value: '0x186a0'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: CORE_TIMER_TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart_bootloader}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: btl_TIMER_dependency}
- type: ElementPosition
  attributes: {x: '24', y: '182', id: core_timer}
