files:
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
  logicalPath: config/pic32mz_das_sk/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3BBD6EF8C254B1A1FEE1B18437A03203
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_das_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 9906B1B9095AFEEFDD72C23237F886D1
  logicalPath: config/pic32mz_das_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9906B1B9095AFEEFDD72C23237F886D1
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mz_das_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D1F0973118394557294B86454F440B2E
  logicalPath: config/pic32mz_das_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: D1F0973118394557294B86454F440B2E
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mz_das_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: B78784342D92F137A0446EBC260A199D
  logicalPath: config/pic32mz_das_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B78784342D92F137A0446EBC260A199D
- generatedChecksum: AA39ADD03AAD8520FCBD9FB091A31487
  logicalPath: config/pic32mz_das_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AA39ADD03AAD8520FCBD9FB091A31487
- generatedChecksum: 6EEAD941F5979497535D0CA5CFA8B216
  logicalPath: config/pic32mz_das_sk/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6EEAD941F5979497535D0CA5CFA8B216
- generatedChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
  logicalPath: config/pic32mz_das_sk
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
- generatedChecksum: F8E5A602361062C584BFD545E44A2C6F
  logicalPath: config/pic32mz_das_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8E5A602361062C584BFD545E44A2C6F
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: A5AA916F4E5F86FBD753F270E78EA5B8
  logicalPath: config/pic32mz_das_sk/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: A5AA916F4E5F86FBD753F270E78EA5B8
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mz_das_sk
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 6707BDC3F251452170841D10D69DB1F1
  logicalPath: config/pic32mz_das_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 6707BDC3F251452170841D10D69DB1F1
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_das_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_das_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_das_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
  logicalPath: config/pic32mz_das_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 0EA600D4DBA17C02F74FD5C7BE8F56B0
- generatedChecksum: 44A9EFA06536DE1713738D859242B11C
  logicalPath: config/pic32mz_das_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 44A9EFA06536DE1713738D859242B11C
- generatedChecksum: FFF8E458FD7BB6E5CED45D1549F80253
  logicalPath: config/pic32mz_das_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFF8E458FD7BB6E5CED45D1549F80253
- generatedChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
  logicalPath: config/pic32mz_das_sk/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: ABEBE7D57FD85725DCF9E71E09924F4A
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mz_das_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: CAC44960D20AEC03CF4B325A1CD2877C
  logicalPath: config/pic32mz_das_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CAC44960D20AEC03CF4B325A1CD2877C
- generatedChecksum: null
  logicalPath: config/pic32mz_das_sk
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_das_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
