configName: pic32mz_w1_curiosity
folderName: pic32mz_w1_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..
processor: PIC32MZ1025W104132
projectName: uart_bootloader_test_app_pic32mz_w1_curiosity
settings:
  PackageFilter: bootloader;bootloader_apps_can;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_spi;bootloader_apps_uart;bootloader_apps_uart_44;bsp;core;core_apps_pic32cm_le_ls;core_apps_pic32cm_mc00;core_apps_pic32cxbz2_wbz45;core_apps_pic32cxbz3_wbz3;core_apps_pic32cx_bz24_bz25_Sumanth_wkg_brch;core_apps_pic32cz_ca;core_apps_pic32mk;core_apps_pic32mz_w1;core_apps_sam_c20_c21;core_apps_sam_d5x_e5x;core_apps_sam_e70_s70_v70_v71;core_apps_sam_g55;core_apps_sam_l21;core_apps_sam_l22;core_apps_sam_rh707;csp;csp_apps_cec173x;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32cm_jh00_jh01_Sumanth_wkg_brch;csp_apps_pic32cm_le_ls;csp_apps_pic32cm_mc00;csp_apps_pic32cxbz2_wbz45;csp_apps_pic32cxbz3_wbz3;csp_apps_pic32cxbz3_wbz3_Sumanth_wkg_brch;csp_apps_pic32cx_bz24_bz25_Sumanth_wkg_brch;csp_apps_pic32cx_mt;csp_apps_pic32cz_ca;csp_apps_pic32mk;csp_apps_pic32mm;csp_apps_pic32mz_da;csp_apps_pic32mz_w1;csp_apps_sam_a5d2;csp_apps_sam_a7g5;csp_apps_sam_c20_c21;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_e70_s70_v70_v71;csp_apps_sam_g55;csp_apps_sam_l21;csp_apps_sam_l21_Tested_backup;csp_apps_sam_l22;csp_apps_sam_rh707;delete_bootloader_apps_i2c_working;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.6.217\atdf\PIC32MZ1025W104132.atdf
