files:
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: A246A582FCD0A29F9F52A5BBE25987D7
  logicalPath: config/pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A246A582FCD0A29F9F52A5BBE25987D7
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: B77696BF832A298EE01AB2BF801FE285
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B77696BF832A298EE01AB2BF801FE285
- generatedChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
  logicalPath: config/pic32mk_gp_db/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: F8BB2BAA74068083A80E6E229BBCF3E3
- generatedChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71E5ACC69F93C73A5A6A0357AC92D694
- generatedChecksum: 687E241CD8B6A5375DA804DD5B53EC72
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 687E241CD8B6A5375DA804DD5B53EC72
- generatedChecksum: 171F05807BE1DA35533DFD415B32C57E
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 171F05807BE1DA35533DFD415B32C57E
- generatedChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
  logicalPath: config/pic32mk_gp_db
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0CB9B700E11C25ACB2D5C30F4365F1F1
- generatedChecksum: AEAD678D52A900BF13F45EFDA811BC10
  logicalPath: config/pic32mk_gp_db/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEAD678D52A900BF13F45EFDA811BC10
- generatedChecksum: null
  logicalPath: ''
  name: app_mips.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3FEAC95DFD4DE6C583AAACC2E785135D
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3FEAC95DFD4DE6C583AAACC2E785135D
- generatedChecksum: 76016C9804D6DE17B74C92D82294562E
  logicalPath: config/pic32mk_gp_db
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 76016C9804D6DE17B74C92D82294562E
- generatedChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
  logicalPath: config/pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9E7BBC6F6BBB3C770EFC72EE2BE887B3
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_gp_db
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 848286252841AFE9AEEC10E0CD784605
  logicalPath: config/pic32mk_gp_db/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 848286252841AFE9AEEC10E0CD784605
- generatedChecksum: F666CF132ECA91F43C2A25389BA2AC28
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F666CF132ECA91F43C2A25389BA2AC28
- generatedChecksum: 0D9A237E654AC0456092675C1A8A922A
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D9A237E654AC0456092675C1A8A922A
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mk_gp_db
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
