format_version: v1.0
type: UniqueComponent
attributes: {id: stdio}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: DEBUG_PERIPHERAL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: stdio, value: uart6}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart6}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: UART6_UART}
- type: ElementPosition
  attributes: {x: '271', y: '219', id: stdio}
