configName: sam_l10_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAML10E16A
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML10_DFP\3.2.68\atdf\ATSAML10E16A.atdf
