configName: sam_e54_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAME54P20A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAME54_DFP\3.2.53\atdf\ATSAME54P20A.atdf
