configName: pic32mz_w1_curiosity
folderName: pic32mz_w1_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\harmony_3
processor: PIC32MZ1025W104132
projectName: uart_bootloader_pic32mz_w1_curiosity
settings:
  PackageFilter: bootloader;bootloader_apps_can;bootloader_apps_ethernet;bootloader_apps_i2c;bootloader_apps_sdcard;bootloader_apps_serial_memory;bootloader_apps_uart;bootloader_apps_usb;bsp;core;csp;net;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MZ-W_DFP\1.4.193\atdf\PIC32MZ1025W104132.atdf
