format_version: v1.0
type: UniqueComponent
attributes: {id: uart2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '216'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '0'}
  - type: Comment
    attributes: {id: UART_BRGH_MODE_COMMENT}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: text}
        children:
        - {type: Value, value: '*** High Speed mode 4x baud clock enabled (BRGH =
            1) ***'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '100000000'}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart2, value: '8'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART2_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart_bootloader}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: btl_UART_dependency}
- type: ElementPosition
  attributes: {x: '24', y: '266', id: uart2}
