format_version: v1.0
type: UniqueComponent
attributes: {id: uart_bootloader}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: BTL_DUAL_BANK}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Comment
    attributes: {id: BTL_DUAL_BANK_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: String
    attributes: {id: BTL_SIZE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: '16384'}
  - type: Boolean
    attributes: {id: BTL_TRIGGER_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: BTL_TRIGGER_LEN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '16'}
  - type: String
    attributes: {id: MEM_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: NVM}
  - type: String
    attributes: {id: PERIPH_USED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart_bootloader, value: UART2}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: btl_MEMORY_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVM_MEMORY}
  - type: DirectDependency
    attributes: {id: btl_TIMER_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: core_timer}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: CORE_TIMER_TMR}
  - type: DirectDependency
    attributes: {id: btl_UART_dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: uart2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: UART2_UART}
- type: ElementPosition
  attributes: {x: '311', y: '142', id: uart_bootloader}
