format_version: v1.0
type: UniqueComponent
attributes: {id: uart1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '25'}
  - type: KeyValueSet
    attributes: {id: UART_BRGH}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '1'}
  - type: Integer
    attributes: {id: UART_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '48000000'}
  - type: Boolean
    attributes: {id: UART_INTERRUPT_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: KeyValueSet
    attributes: {id: UART_OPERATING_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
  - type: Boolean
    attributes: {id: UART_RING_BUFFER_MODE_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: 'false'}
  - type: Hex
    attributes: {id: UMODE_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: uart1, value: '0'}
  - type: Boolean
    attributes: {id: USART_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: label}
        children:
        - {type: Value, value: '---'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: stdio, value: 'false'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: UART1_UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: stdio}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: UART}
- type: ElementPosition
  attributes: {x: '115', y: '196', id: uart1}
