configName: sam_c21n_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../..
processor: ATSAMC21N18A
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;csp;expresslogic_threadx;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.6.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMC21_DFP\3.2.60\samc21n\atdf\ATSAMC21N18A.atdf
